apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "common.metadataNamespace" $ | nindent 2 }}
  name: {{ .Values.configMap.name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
{{- with .Values.configMap.data }}
data:
{{- toYaml . | nindent 2 }}
{{- end }}